version: '3.9'

services:
  app:
    build: ./safepass-app
    working_dir: /backend/
    volumes:
      - ./django-api-portfolio:/backend
    ports:
      - "8000:8000"
    command: ["sh", "-c", "python manage.py runserver 0.0.0.0:8000"]


  nginx:
      image: nginx:latest
      volumes:
        - app_static_volume:/backend/
        - ./nginx/conf.d/queb-online.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
      depends_on:
        - app




volumes:
  app_static_volume:
